# Generated by Django 4.0.5 on 2023-10-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField(null=True)),
                ('nid_number', models.CharField(max_length=20)),
                ('nid_front', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Front)')),
                ('nid_back', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Back)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('appointment', models.FileField(blank=True, null=True, upload_to='appointment/')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('joined_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 492907), null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='employee_set', related_query_name='employee', to='auth.group', verbose_name='roles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
