# Generated by Django 4.2.3 on 2023-09-26 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_employee_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='employee_set', related_query_name='employee', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 11, 3, 1, 500317), null=True),
        ),
    ]
