# Generated by Django 4.2.3 on 2023-09-26 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employee_groups_alter_employee_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='groups',
            new_name='roles',
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 11, 6, 8, 704296), null=True),
        ),
    ]
