# Generated by Django 4.0.5 on 2023-10-29 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 29, 16, 56, 46, 426279), null=True),
        ),
    ]
