# Generated by Django 4.2.3 on 2023-09-26 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_groups_employee_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 26, 11, 7, 21, 648468), null=True),
        ),
    ]
