# Generated by Django 4.0.5 on 2023-10-22 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='upload')),
                ('location', models.TextField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='SupplierBeneficaries',
            fields=[
                ('beneficaries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.beneficaries')),
                ('brand', models.ManyToManyField(blank=True, null=True, to='suppliers.brands')),
            ],
            bases=('globalapp2.beneficaries',),
        ),
        migrations.CreateModel(
            name='Metarials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.JSONField()),
                ('dimenssion', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 682324), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('brand', models.ManyToManyField(blank=True, null=True, to='suppliers.brands')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_type', to='globalapp2.typess')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_unit', to='globalapp2.typess')),
            ],
        ),
    ]
