# Generated by Django 4.2.3 on 2023-09-30 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_metarials'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 30, 10, 23, 3, 99573), null=True),
        ),
        migrations.AddField(
            model_name='metarials',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='metarials',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
