# Generated by Django 4.2.3 on 2023-09-30 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_metarials_created_at_metarials_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 30, 12, 41, 31, 119072), null=True),
        ),
    ]
