# Generated by Django 4.0.5 on 2023-10-26 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_metarials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 16, 51, 22, 569502), null=True),
        ),
    ]
