# Generated by Django 4.0.5 on 2024-03-05 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_alter_metarials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 5, 13, 7, 36, 210847), null=True),
        ),
    ]
