# Generated by Django 4.0.5 on 2024-03-06 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_alter_metarials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 6, 10, 56, 32, 698959), null=True),
        ),
    ]
