# Generated by Django 4.0.5 on 2024-03-06 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_alter_metarials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 6, 11, 11, 31, 778845), null=True),
        ),
    ]
