# Generated by Django 4.2.3 on 2023-10-18 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0080_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('inventory', '0001_initial'),
        ('suppliers', '0039_alter_metarials_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='metarials',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='metarials',
            name='dimenssion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metarials',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_type', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='metarials',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_unit', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='supplierbeneficaries',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 18, 18, 5, 51, 460880), null=True),
        ),
        migrations.DeleteModel(
            name='TestBeneficaries',
        ),
    ]
