# Generated by Django 4.0.5 on 2023-10-21 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0081_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('suppliers', '0040_metarials_brand_metarials_dimenssion_metarials_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='upload')),
                ('location', models.TextField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 21, 12, 4, 47, 288841), null=True),
        ),
        migrations.AlterField(
            model_name='metarials',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='suppliers.brands'),
        ),
        migrations.AlterField(
            model_name='supplierbeneficaries',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, to='suppliers.brands'),
        ),
    ]
