# Generated by Django 4.0.5 on 2023-10-21 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0041_brands_alter_metarials_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metarials',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 21, 12, 43, 55, 906853), null=True),
        ),
    ]
