# Generated by Django 4.2.3 on 2023-08-11 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField(null=True)),
                ('NID_number', models.CharField(max_length=20)),
                ('nid_front', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Front)')),
                ('nid_back', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Back)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('appointment', models.FileField(blank=True, null=True, upload_to='appointment/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Banned', 'Banned'), ('Left', 'Left')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 16, 50, 41, 389970), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficaries',
            fields=[
                ('introinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='global.introinfo')),
            ],
            bases=('global.introinfo',),
        ),
        migrations.AddField(
            model_name='introinfo',
            name='phone_number',
            field=models.ManyToManyField(to='global.phonenumber'),
        ),
    ]
