# Generated by Django 4.2.3 on 2023-08-11 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0002_beneficaries_name_alter_beneficaries_introinfo_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 17, 2, 46, 187591), null=True),
        ),
    ]
