# Generated by Django 4.2.3 on 2023-08-11 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0003_alter_introinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 17, 5, 4, 850203), null=True),
        ),
    ]
