# Generated by Django 4.2.3 on 2023-07-22 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('NID_number', models.CharField(max_length=20)),
                ('nid_front', models.FileField(upload_to='nid/', verbose_name='NID Image (Front)')),
                ('nid_back', models.FileField(upload_to='nid/', verbose_name='NID Image (Back)')),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('appointment', models.FileField(upload_to='appointment/')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Banned', 'Banned')], max_length=50, null=True)),
                ('joined_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 22, 18, 40, 2, 381806), null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.ManyToManyField(to='users.phonenumber')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
