# Generated by Django 4.2.3 on 2023-08-09 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment',
            field=models.FileField(blank=True, null=True, upload_to='appointment/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 9, 15, 1, 2, 259457), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nid_back',
            field=models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Back)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nid_front',
            field=models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Front)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
