# Generated by Django 4.2.3 on 2023-08-09 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='present_address',
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 9, 17, 13, 7, 727952), null=True),
        ),
    ]
