# Generated by Django 4.2.3 on 2023-08-11 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_address_employee_present_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 16, 50, 41, 386980), null=True),
        ),
    ]
