# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseByProperty',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('reciept', models.FileField(upload_to='upload')),
                ('expense_date', models.DateField()),
                ('expenser_name', models.CharField(max_length=50)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('city_corporation', models.CharField(max_length=20)),
                ('ward_no', models.CharField(max_length=20)),
                ('post_office', models.CharField(max_length=20)),
                ('police_station', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('project_size', models.FloatField()),
                ('basement_no', models.IntegerField()),
                ('number_of_elevator', models.IntegerField()),
                ('number_of_stairs', models.IntegerField()),
                ('number_of_parking', models.IntegerField()),
                ('number_of_shops', models.IntegerField()),
                ('work_start_date', models.DateField()),
                ('expected_handover_date', models.DateField()),
                ('commarcial_floor', models.IntegerField()),
                ('commarcial_unit', models.IntegerField()),
                ('residential_floor', models.IntegerField()),
                ('residential_unit', models.IntegerField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='projectProgress',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('note', models.TextField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='propertyInstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('installment_date', models.DateField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='propertyModels',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('code', models.CharField(max_length=10)),
                ('side', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='propertyPurchase',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('down_payment', models.FloatField()),
                ('installment', models.IntegerField()),
                ('facilities', models.JSONField()),
                ('installment_duration', models.IntegerField()),
                ('final_return', models.DateField(blank=True, null=True)),
                ('due_amount', models.FloatField(blank=True, null=True)),
                ('due_installment', models.FloatField(blank=True, null=True)),
                ('handover_status', models.BooleanField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.FloatField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='UnitModels',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('unit_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('Commarcial', 'Commarcial'), ('Ressidential', 'Ressidential')], max_length=50, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('unit_property', models.ManyToManyField(blank=True, null=True, to='projects.propertymodels')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
