# Generated by Django 4.2.3 on 2023-10-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0050_alter_common_created_at_alter_commonmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('city_corporation', models.CharField(max_length=20)),
                ('ward_no', models.CharField(max_length=20)),
                ('post_office', models.CharField(max_length=20)),
                ('police_station', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('project_size', models.FloatField()),
                ('basement_no', models.IntegerField()),
                ('number_of_elevator', models.IntegerField()),
                ('number_of_stairs', models.IntegerField()),
                ('number_of_parking', models.IntegerField()),
                ('number_of_shops', models.IntegerField()),
                ('work_start_date', models.DateField()),
                ('expected_handover_date', models.DateField()),
                ('commarcial_floor', models.IntegerField()),
                ('commarcial_unit', models.IntegerField()),
                ('residential_floor', models.IntegerField()),
                ('residential_unit', models.IntegerField()),
                ('project_size_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_size_type', to='globalapp2.types')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='globalapp2.types')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
