# Generated by Django 4.0.5 on 2023-12-06 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globalapp2', '0002_introinfo_author_id_phonenumber_ben_id_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensebyproperty',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensebyproperty',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels'),
        ),
        migrations.AddField(
            model_name='expensebyproperty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_size_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_size_type', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='wp_ids',
            field=models.ManyToManyField(to='projects.workprogress'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='purchase_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.propertypurchase'),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerbeneficaries'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='project_id',
            field=models.ManyToManyField(to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='property_id',
            field=models.ManyToManyField(to='projects.propertymodels'),
        ),
        migrations.AlterField(
            model_name='propertypurchase',
            name='final_return',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
