# Generated by Django 4.2.3 on 2023-10-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0058_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.FloatField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='projectProgress',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('note', models.TextField()),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('wp_ids', models.ManyToManyField(to='projects.workprogress')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
