# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('globalapp2', '0002_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypurchase',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerbeneficaries'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='project_id',
            field=models.ManyToManyField(to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='property_id',
            field=models.ManyToManyField(to='projects.propertymodels'),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels'),
        ),
        migrations.AddField(
            model_name='propertyinstallment',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertypurchase'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='wp_ids',
            field=models.ManyToManyField(to='projects.workprogress'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_size_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_size_type', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type', to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='expensebyproperty',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensebyproperty',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels'),
        ),
        migrations.AddField(
            model_name='expensebyproperty',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
    ]
