# Generated by Django 4.2.3 on 2023-10-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0061_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0002_workprogress_projectprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('code', models.CharField(max_length=10)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
