# Generated by Django 4.2.3 on 2023-10-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0062_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0003_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='propertyModels',
        ),
    ]
