# Generated by Django 4.2.3 on 2023-10-05 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('globalapp2', '0063_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0004_rename_property_propertymodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyPurchase',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('down_payment', models.FloatField()),
                ('installment', models.IntegerField()),
                ('facilities', models.JSONField()),
                ('installment_duration', models.IntegerField()),
                ('final_return', models.DateField()),
                ('due_amount', models.FloatField()),
                ('due_installment', models.FloatField()),
                ('handover_status', models.BooleanField()),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customerbeneficaries')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.types')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
