# Generated by Django 4.2.3 on 2023-10-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0064_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_propertypurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='propertyInstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('installment_date', models.DateField()),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.propertypurchase')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='ExpenseByProperty',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('reciept', models.FileField(upload_to='upload')),
                ('expense_date', models.DateField()),
                ('expenser_name', models.CharField(max_length=50)),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.propertymodels')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.types')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
