# Generated by Django 4.2.3 on 2023-10-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0067_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0006_propertyinstallment_expensebyproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodels',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymodels',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.types'),
        ),
        migrations.CreateModel(
            name='UnitModels',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('unit_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('unit_property', models.ManyToManyField(to='projects.propertymodels')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
