# Generated by Django 4.2.3 on 2023-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_propertymodels_project_id_propertymodels_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodels',
            name='unit_property',
            field=models.ManyToManyField(blank=True, null=True, to='projects.propertymodels'),
        ),
    ]
