# Generated by Django 4.2.3 on 2023-10-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_unitmodels_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodels',
            name='type',
            field=models.CharField(blank=True, choices=[('Commarcial', 'Commarcial'), ('Ressidential', 'Ressidential')], max_length=50, null=True),
        ),
    ]
