# Generated by Django 4.2.3 on 2023-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_expensebyproperty_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertypurchase',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='propertypurchase',
            name='property_id',
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='project_id',
            field=models.ManyToManyField(to='projects.projectinfo'),
        ),
        migrations.AddField(
            model_name='propertypurchase',
            name='property_id',
            field=models.ManyToManyField(to='projects.propertymodels'),
        ),
    ]
