# Generated by Django 4.2.3 on 2023-10-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_propertypurchase_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypurchase',
            name='due_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypurchase',
            name='due_installment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypurchase',
            name='final_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
