# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlog',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='giver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_activity', to='loan.loanbeneficaries'),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loantransactions'),
        ),
        migrations.AddField(
            model_name='loanlog',
            name='taker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_activity', to='loan.loanbeneficaries'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='giver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_installment', to='loan.loanbeneficaries'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loantransactions'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='taker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_installment', to='loan.loanbeneficaries'),
        ),
    ]
