# Generated by Django 4.2.3 on 2023-09-14 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0008_alter_loaninstallment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstallment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 14), null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.date(2023, 9, 14), null=True),
        ),
        migrations.CreateModel(
            name='LoanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, default=datetime.date(2023, 9, 14), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('giver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_activity', to='loan.loanbeneficaries')),
                ('loan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loantransactions')),
                ('taker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_activity', to='loan.loanbeneficaries')),
            ],
        ),
    ]
