# Generated by Django 4.0.5 on 2024-03-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0018_alter_common_created_at_alter_commonmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsListing',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('depriciation_amount', models.CharField(max_length=100)),
                ('current_price', models.CharField(max_length=100)),
                ('depriciation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
