# Generated by Django 4.0.5 on 2024-03-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetssell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssell',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetslisting'),
        ),
    ]
