# Generated by Django 4.0.5 on 2024-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetssell_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetssell',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assetssell',
            name='date',
            field=models.DateField(),
        ),
    ]
