# Generated by Django 4.0.5 on 2024-03-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetssell_documents_alter_assetssell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetssell',
            name='documents',
            field=models.FileField(upload_to=''),
        ),
    ]
