# Generated by Django 4.0.5 on 2023-10-22 14:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 493908), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 495902), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField(null=True)),
                ('nid_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_digit', message='Only digits are allowed.', regex='^\\d+$')])),
                ('nid_front', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Front)')),
                ('nid_back', models.FileField(blank=True, null=True, upload_to='nid/', verbose_name='NID Image (Back)')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 493908), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Contractor', 'Contractor'), ('Suppliers', 'Suppliers'), ('Employee', 'Land Owners'), ('Land Owners', 'Employees'), ('Company Owners', 'Company Owners'), ('Loan Beneficaries', 'Loan Beneficaries')], max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 494903), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppLabels',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='Beneficaries',
            fields=[
                ('introinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.introinfo')),
            ],
            bases=('globalapp2.introinfo',),
        ),
        migrations.CreateModel(
            name='Typess',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
