# Generated by Django 4.2.3 on 2023-08-31 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introinfo',
            old_name='NID_number',
            new_name='nid_number',
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 10, 53, 6, 171029), null=True),
        ),
    ]
