# Generated by Django 4.2.3 on 2023-08-31 05:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0002_rename_nid_number_introinfo_nid_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 11, 37, 46, 506766), null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='nid_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_digit', message='Only digits are allowed.', regex='^\\d+$')]),
        ),
    ]
