# Generated by Django 4.2.3 on 2023-08-31 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0008_phonenumber_ben_id_phonenumber_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 17, 51, 14, 472794), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 17, 51, 14, 481804), null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 17, 51, 14, 472794), null=True),
        ),
    ]
