# Generated by Django 4.2.3 on 2023-09-10 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0013_alter_common_created_at_alter_introinfo_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introinfo',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='common',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 10, 16, 9, 50, 720640), null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 10, 16, 9, 50, 720640), null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 10, 16, 9, 50, 720640), null=True),
        ),
    ]
