# Generated by Django 4.2.3 on 2023-09-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvhandler', '0002_uploadcsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadcsv',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='uploadcsv',
            name='app_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
