# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('documents', models.FileField(upload_to='')),
                ('expenser_name', models.CharField(max_length=50)),
                ('expense_date', models.DateTimeField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('documents', models.FileField(upload_to='')),
                ('income_name', models.CharField(max_length=50)),
                ('income_date', models.DateTimeField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
