# Generated by Django 4.2.3 on 2023-10-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globalapp2', '0060_alter_common_created_at_alter_commonmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('documents', models.FileField(upload_to='')),
                ('expenser_name', models.CharField(max_length=50)),
                ('expense_date', models.DateTimeField()),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('documents', models.FileField(upload_to='')),
                ('expenser_name', models.CharField(max_length=50)),
                ('expense_date', models.DateTimeField()),
                ('author_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
