# Generated by Django 4.2.3 on 2023-10-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='expense_date',
            new_name='income_date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='expenser_name',
            new_name='income_name',
        ),
    ]
