# Generated by Django 4.0.5 on 2023-10-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 700504), null=True)),
                ('work_hour', models.IntegerField()),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.IntegerField(blank=True, null=True)),
                ('leave_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('apply_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 700669), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('days', models.IntegerField(blank=True, null=True)),
                ('loan', models.IntegerField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 20, 8, 46, 700669), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
