# Generated by Django 4.2.3 on 2023-09-07 23:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0002_attendance_status_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 5, 15, 59, 446168), null=True),
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.IntegerField(blank=True, null=True)),
                ('leave_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('apply_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 5, 15, 59, 446168), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
