# Generated by Django 4.2.3 on 2023-09-07 23:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0003_alter_attendance_date_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 5, 29, 59, 194596), null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='apply_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 5, 29, 59, 194596), null=True),
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('days', models.IntegerField(blank=True, null=True)),
                ('loan', models.IntegerField(blank=True, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 5, 29, 59, 194596), null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_salary', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
