# Generated by Django 4.2.3 on 2023-07-17 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_joined_at_alter_myuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='joined_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 19, 9, 5, 937119), null=True),
        ),
    ]
