# Generated by Django 4.2.3 on 2023-10-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0080_alter_common_created_at_alter_commonmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='upload')),
                ('location', models.TextField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
