# Generated by Django 4.0.5 on 2023-10-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_propertypurchase_due_amount_and_more'),
        ('globalapp2', '0081_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('suppliers', '0041_brands_alter_metarials_created_at_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('sr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('amount', models.FloatField()),
                ('amount_due', models.FloatField()),
                ('amount_advance', models.FloatField()),
                ('purchase_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplierbeneficaries')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
