# Generated by Django 4.0.5 on 2023-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdispatch',
            name='check_status',
            field=models.CharField(blank=True, choices=[('Check in', 'Check in'), ('Check out', 'Check out'), ('Return', 'Return'), ('Swap', 'Swap')], max_length=50, null=True),
        ),
    ]
