# Generated by Django 4.0.5 on 2023-10-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_propertypurchase_due_amount_and_more'),
        ('suppliers', '0042_alter_metarials_created_at'),
        ('globalapp2', '0082_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('inventory', '0002_materialpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDispatch',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('quantity', models.FloatField()),
                ('metarial', models.ManyToManyField(to='suppliers.metarials')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_type', to='globalapp2.typess')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_unit', to='globalapp2.typess')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='commonmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='purchase_for',
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='vendor_id',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='MaterialPurchase',
        ),
    ]
