# Generated by Django 4.0.5 on 2023-12-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdispatch',
            name='check_status',
            field=models.CharField(blank=True, choices=[('Check in', 'Check in'), ('Check out', 'Check out'), ('Return', 'Return'), ('Swap', 'Swap')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialdispatch',
            name='inventory_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventories'),
        ),
    ]
