# Generated by Django 4.0.5 on 2023-10-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_materialdispatch_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdispatch',
            name='inventory_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventories'),
        ),
    ]
