# Generated by Django 4.0.5 on 2023-10-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_propertypurchase_due_amount_and_more'),
        ('wearhouse', '0003_materialinstallment'),
        ('inventory', '0003_materialdispatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('materialpurchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wearhouse.materialpurchase')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
            ],
            bases=('wearhouse.materialpurchase',),
        ),
    ]
