# Generated by Django 4.2.3 on 2023-08-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0004_alter_introinfo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanBeneficaries',
            fields=[
                ('beneficaries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.beneficaries')),
            ],
            bases=('globalapp2.beneficaries',),
        ),
    ]
