# Generated by Django 4.2.3 on 2023-08-14 11:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('return_type', models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=50, null=True)),
                ('interest', models.FloatField()),
                ('instalment', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('interested_amount', models.FloatField()),
                ('return_amount', models.FloatField()),
                ('current_amount', models.FloatField()),
                ('status', models.BooleanField()),
                ('last_payed', models.DateField()),
                ('created_at', models.DateField(default=datetime.datetime(2023, 8, 14, 11, 6, 20, 202549, tzinfo=datetime.timezone.utc))),
                ('giver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_loans', to='loan.loanbeneficaries')),
                ('taker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_loans', to='loan.loanbeneficaries')),
            ],
        ),
    ]
