# Generated by Django 4.2.3 on 2023-08-14 11:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loantransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 11, 9, 47, 63894, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='instalment',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
