# Generated by Django 4.2.3 on 2023-08-15 05:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loantransactions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 5, 30, 42, 260691, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='current_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='last_payed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='return_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
