# Generated by Django 4.2.3 on 2023-08-15 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loantransactions_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 5, 40, 17, 94250, tzinfo=datetime.timezone.utc)),
        ),
    ]
