# Generated by Django 4.2.3 on 2023-08-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loantransactions_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransactions',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 7, 32, 13, 571740, tzinfo=datetime.timezone.utc)),
        ),
    ]
