# Generated by Django 4.2.3 on 2023-08-30 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0012_remove_introinfo_phone_number_phonenumber_name_and_more'),
        ('loan', '0007_loantransactions_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbeneficaries',
            name='phone_number',
            field=models.ManyToManyField(to='globalapp2.phonenumber'),
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 8, 26, 6, 512567, tzinfo=datetime.timezone.utc)),
        ),
    ]
