# Generated by Django 4.2.3 on 2023-08-30 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loanbeneficaries_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 30, 8, 39, 45, 947581, tzinfo=datetime.timezone.utc)),
        ),
    ]
