# Generated by Django 4.2.3 on 2023-08-31 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loantransactions_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanbeneficaries',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='loantransactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 3, 53, 54, 805305, tzinfo=datetime.timezone.utc)),
        ),
    ]
