# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignContractor',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('rate', models.FloatField()),
                ('rate_per_work', models.FloatField()),
                ('unit', models.IntegerField()),
                ('work_order_amount', models.FloatField()),
                ('payed_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
                ('workers', models.IntegerField()),
                ('worker_payement', models.FloatField()),
                ('security_money_percentage', models.FloatField()),
                ('security_amount', models.FloatField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='ContractorGarrentor',
            fields=[
                ('introinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.introinfo')),
                ('role', models.CharField(max_length=100)),
            ],
            bases=('globalapp2.introinfo',),
        ),
        migrations.CreateModel(
            name='ContructorsBeneficaries',
            fields=[
                ('beneficaries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.beneficaries')),
            ],
            bases=('globalapp2.beneficaries',),
        ),
        migrations.CreateModel(
            name='ContractorPaymnet',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('worker', models.IntegerField()),
                ('payment', models.FloatField()),
                ('contructor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contructors.contructorsbeneficaries')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
