# Generated by Django 4.2.3 on 2023-09-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0019_alter_common_created_at_alter_introinfo_created_at_and_more'),
        ('contructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorGarrentor',
            fields=[
                ('introinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.introinfo')),
                ('role', models.CharField(max_length=100)),
            ],
            bases=('globalapp2.introinfo',),
        ),
    ]
