# Generated by Django 4.0.5 on 2024-03-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0017_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('contructors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncontractor',
            name='contractor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
        migrations.AddField(
            model_name='contructorsbeneficaries',
            name='contractor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
    ]
