# Generated by Django 4.2.3 on 2023-09-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contructors', '0002_contractorgarrentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorgarrentor',
            name='contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contructors.contructorsbeneficaries'),
        ),
    ]
