# Generated by Django 4.2.3 on 2023-10-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0059_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0002_workprogress_projectprogress'),
        ('contructors', '0003_contractorgarrentor_contractor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPaymnet',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('worker', models.IntegerField()),
                ('payment', models.FloatField()),
                ('contructor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contructors.contructorsbeneficaries')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='AssignContractor',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('rate', models.FloatField()),
                ('rate_per_work', models.FloatField()),
                ('unit', models.IntegerField()),
                ('work_order_amount', models.FloatField()),
                ('payed_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
                ('workers', models.IntegerField()),
                ('worker_payement', models.FloatField()),
                ('security_money_percentage', models.FloatField()),
                ('security_amount', models.FloatField()),
                ('contructor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contructors.contructorsbeneficaries')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
