# Generated by Django 4.2.3 on 2023-10-12 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0074_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('contructors', '0004_contractorpaymnet_assigncontractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorpaymnet',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess'),
        ),
    ]
