# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(upload_to='logo')),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('phone_number', models.ManyToManyField(to='globalapp2.phonenumber')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
