# Generated by Django 4.0.5 on 2023-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0005_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='phone_number',
            field=models.ManyToManyField(blank=True, null=True, to='globalapp2.phonenumber'),
        ),
    ]
