# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('globalapp2', '0001_initial'),
        ('inglobal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchases',
            fields=[
                ('materialcommon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inglobal.materialcommon')),
            ],
            bases=('inglobal.materialcommon',),
        ),
        migrations.CreateModel(
            name='WearhouseItem',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('inventory_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productinventories')),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.materialpurchases')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='MaterialInstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('recieve_date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.materialpurchases')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
