# Generated by Django 4.0.5 on 2023-12-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_metarials_created_at'),
        ('projects', '0002_expensebyproperty_author_id_and_more'),
        ('globalapp2', '0002_introinfo_author_id_phonenumber_ben_id_and_more'),
        ('wearhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearhouseitem',
            name='due_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wearhouseitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WarehouseMaterialDispatch',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('quantity', models.FloatField()),
                ('check_status', models.CharField(blank=True, choices=[('Check in', 'Check in'), ('Check out', 'Check out')], max_length=50, null=True)),
                ('metarial', models.ManyToManyField(to='suppliers.metarials')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdispatch_type', to='globalapp2.typess')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdispatch_unit', to='globalapp2.typess')),
                ('warehouse_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.wearhouseitem')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='MaterialPaymentinstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.materialpurchases')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
