# Generated by Django 4.0.5 on 2023-10-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_metarials_created_at'),
        ('globalapp2', '0004_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('projects', '0002_initial'),
        ('wearhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearhouseitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WarehouseMaterialDispatch',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('quantity', models.FloatField()),
                ('metarial', models.ManyToManyField(to='suppliers.metarials')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdispatch_type', to='globalapp2.typess')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wdispatch_unit', to='globalapp2.typess')),
                ('warehouse_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectinfo')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
