# Generated by Django 4.0.5 on 2023-10-22 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0087_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('wearhouse', '0002_alter_materialpurchase_purchase_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('recieve_date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.materialpurchase')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalapp2.typess')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
