# Generated by Django 4.0.5 on 2023-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0003_warehousematerialdispatch_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearhouseitem',
            name='due_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
