# Generated by Django 4.0.5 on 2023-10-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0004_wearhouseitem_due_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousematerialdispatch',
            name='check_status',
            field=models.CharField(blank=True, choices=[('Check in', 'Check in'), ('Check out', 'Check out')], max_length=50, null=True),
        ),
    ]
