# Generated by Django 4.0.5 on 2023-10-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0009_alter_common_created_at_alter_commonmodel_created_at_and_more'),
        ('wearhouse', '0005_warehousematerialdispatch_check_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPaymentinstallment',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('purchase_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.materialpurchases')),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
