# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatRent',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('advanced_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='RentCollection',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('rent_amount', models.FloatField()),
                ('due_amount', models.FloatField()),
                ('rent_date', models.DateField()),
            ],
            bases=('globalapp2.commonmodel',),
        ),
        migrations.CreateModel(
            name='RenterBeneficaries',
            fields=[
                ('beneficaries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.beneficaries')),
            ],
            bases=('globalapp2.beneficaries',),
        ),
        migrations.CreateModel(
            name='RepairRecords',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('reason', models.TextField()),
                ('amount', models.FloatField()),
                ('expensed_by', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Renter', 'Renter')], max_length=50, null=True)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
