# Generated by Django 4.2.3 on 2023-10-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0065_alter_common_created_at_alter_commonmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterBeneficaries',
            fields=[
                ('beneficaries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.beneficaries')),
            ],
            bases=('globalapp2.beneficaries',),
        ),
    ]
