# Generated by Django 4.2.3 on 2023-08-11 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficaries',
            name='name',
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 17, 17, 13, 300222), null=True),
        ),
    ]
