# Generated by Django 4.2.3 on 2023-08-11 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0002_remove_beneficaries_name_alter_introinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficaries',
            name='giver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficaries',
            name='relation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 17, 27, 56, 300103), null=True),
        ),
    ]
