# Generated by Django 4.2.3 on 2023-08-11 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0003_beneficaries_giver_name_beneficaries_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 11, 17, 35, 54, 777846), null=True),
        ),
    ]
