# Generated by Django 4.2.3 on 2023-08-12 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0004_alter_introinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='introinfo',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 12, 18, 23, 16, 247021), null=True),
        ),
    ]
