# Generated by Django 4.2.3 on 2023-08-31 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0016_alter_introinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficaries',
            name='giver_name',
        ),
        migrations.RemoveField(
            model_name='beneficaries',
            name='relation',
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 9, 53, 54, 799114), null=True),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
