# Generated by Django 4.2.3 on 2023-08-31 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp2', '0018_alter_introinfo_created_at_alter_introinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 31, 10, 13, 50, 290518), null=True),
        ),
    ]
