# Generated by Django 4.0.5 on 2023-10-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globalapp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCommon',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp2.commonmodel')),
                ('sr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('amount', models.FloatField()),
                ('amount_due', models.FloatField(blank=True, null=True)),
                ('amount_advance', models.FloatField()),
                ('quantity', models.FloatField()),
                ('recieved_quantity', models.FloatField(blank=True, null=True)),
                ('due_quantity', models.FloatField(blank=True, null=True)),
            ],
            bases=('globalapp2.commonmodel',),
        ),
    ]
